repos:
  - repo: local
    hooks:
      - id: find-requirements
        name: find-requirements
        entry: python find_libraries.py
        language: python
        pass_filenames: false

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/psf/black
    rev: 23.12.0
    hooks:
      - id: black

  # ------------------------------------
  # NEW: Ruff replaces Flake8
  # ------------------------------------
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Check the Ruff releases page for the absolute latest version
    rev: v0.5.0
    hooks:
      # Run the linter
      - id: ruff
        args: [ --fix ]

  - repo: https://github.com/pycqa/pylint
    rev: v3.0.3
    hooks:
      - id: pylint
        args: [
          "--generated-members=cv2.*,player.*,alsaaudio.Mixer",
          "--disable=duplicate-code,line-too-long,too-few-public-methods,broad-exception-caught,unused-argument,import-error",
        ]
